### PR TITLE
Add --socket=cups for printing

### LINKED ISSUE #15: Can't print from Scribus : only "File" is suggested
Hi,

I've just installed latest net.scribus.Scribus from FlatHub and note that it's the 1st time I launch Scribus.

I tried to print my work but I only could save it into a ps file, ready to be print outside Scribus.

Note that for instance org.libreoffice.LibreOffice allow me to print directly

Thanks

Screenshot :
Capture d’écran de 2020-04-12 16-04-12

### PR DESCRIPTION
**Pull request by eszlari**
fixes #15, needs flatpak 1.6

### CODE REVIEW

**Comment by jurf** [comment]
Curious, why the latest SVN revision? Thanks for the work however, wanted to sit down to this for some time but haven’t found the time yet.

**Comment by eszlari** [comment]
I just wanted to make sure, there weren't some printing related fixes since the last release.

But it seems safe to update anyway, the app builds and runs.

**Comment by jurf** [comment]
@aoloe, request for opinion. :slightly_smiling_face: Do you think the latest SVN is fine to ship?

**Comment by aoloe** [comment]
@jurf right now there is lot of (refactoring) activity currently ongoing... but,  yes, most of the time using the latest svn is rather safe.

**Comment by jurf** [comment]
OK, I’ll probably keep up the practice until 1.6 comes out.

**Pull request merged**
